export const minons = {
  ch1: {
    1: {
      name: '',
      img: '',
      attack: 0,
      deffense: 0,
      specialatk: 0,
      specialdef: 0,
      specmoves: [],
      armor: 0,
      hp: 0,
      mp: 0,
      exp: 0,
      gold: 0
    },
    2: {
      name: '',
      img: '',
      attack: 0,
      deffense: 0,
      specialatk: 0,
      specialdef: 0,
      specmoves: [],
      armor: 0,
      hp: 0,
      mp: 0,
      exp: 0,
      gold: 0
    },
    3: {
      name: '',
      img: '',
      attack: 0,
      deffense: 0,
      specialatk: 0,
      specialdef: 0,
      specmoves: [],
      armor: 0,
      hp: 0,
      mp: 0,
      exp: 0,
      gold: 0
    },
    4: {
      name: '',
      img: '',
      attack: 0,
      deffense: 0,
      specialatk: 0,
      specialdef: 0,
      specmoves: [],
      armor: 0,
      hp: 0,
      mp: 0,
      exp: 0,
      gold: 0
    }
  },
  ch2: {
    1: {
      name: '',
      img: '',
      attack: 0,
      deffense: 0,
      specialatk: 0,
      specialdef: 0,
      specmoves: [],
      armor: 0,
      hp: 0,
      mp: 0,
      exp: 0,
      gold: 0
    },
    2: {
      name: '',
      img: '',
      attack: 0,
      deffense: 0,
      specialatk: 0,
      specialdef: 0,
      specmoves: [],
      armor: 0,
      hp: 0,
      mp: 0,
      exp: 0,
      gold: 0
    },
    3: {
      name: '',
      img: '',
      attack: 0,
      deffense: 0,
      specialatk: 0,
      specialdef: 0,
      specmoves: [],
      armor: 0,
      hp: 0,
      mp: 0,
      exp: 0,
      gold: 0
    },
    4: {
      name: '',
      img: '',
      attack: 0,
      deffense: 0,
      specialatk: 0,
      specialdef: 0,
      specmoves: [],
      armor: 0,
      hp: 0,
      mp: 0,
      exp: 0,
      gold: 0
    }
  },
  ch3: {
    1: {
      name: '',
      img: '',
      attack: 0,
      deffense: 0,
      specialatk: 0,
      specialdef: 0,
      specmoves: [],
      armor: 0,
      hp: 0,
      mp: 0,
      exp: 0,
      gold: 0
    },
    2: {
      name: '',
      img: '',
      attack: 0,
      deffense: 0,
      specialatk: 0,
      specialdef: 0,
      specmoves: [],
      armor: 0,
      hp: 0,
      mp: 0,
      exp: 0,
      gold: 0
    },
    3: {
      name: '',
      img: '',
      attack: 0,
      deffense: 0,
      specialatk: 0,
      specialdef: 0,
      specmoves: [],
      armor: 0,
      hp: 0,
      mp: 0,
      exp: 0,
      gold: 0
    },
    4: {
      name: '',
      img: '',
      attack: 0,
      deffense: 0,
      specialatk: 0,
      specialdef: 0,
      specmoves: [],
      armor: 0,
      hp: 0,
      mp: 0,
      exp: 0,
      gold: 0
    }
  },
  ch4: {
    1: {
      name: 'Maintenance Man',
      img: '',
      attack: 0,
      deffense: 0,
      specialatk: 0,
      specialdef: 0,
      specmoves: [],
      armor: 0,
      hp: 0,
      mp: 0,
      exp: 0,
      gold: 0
    },
    2: {
      name: 'Window Cleaner',
      img: '',
      attack: 0,
      deffense: 0,
      specialatk: 0,
      specialdef: 0,
      specmoves: [],
      armor: 0,
      hp: 0,
      mp: 0,
      exp: 0,
      gold: 0
    },
    3: {
      name: 'Recycling Fanatic',
      img: '',
      attack: 0,
      deffense: 0,
      specialatk: 0,
      specialdef: 0,
      specmoves: [],
      armor: 0,
      hp: 0,
      mp: 0,
      exp: 0,
      gold: 0
    },
    4: {
      name: 'Cleaning Crew Thug',
      img: '',
      attack: 0,
      deffense: 0,
      specialatk: 0,
      specialdef: 0,
      specmoves: [],
      armor: 0,
      hp: 0,
      mp: 0,
      exp: 0,
      gold: 0
    }
  },
  ch5: {
    1: {
      name: '',
      img: '',
      attack: 0,
      deffense: 0,
      specialatk: 0,
      specialdef: 0,
      specmoves: [],
      armor: 0,
      hp: 0,
      mp: 0,
      exp: 0,
      gold: 0
    },
    2: {
      name: '',
      img: '',
      attack: 0,
      deffense: 0,
      specialatk: 0,
      specialdef: 0,
      specmoves: [],
      armor: 0,
      hp: 0,
      mp: 0,
      exp: 0,
      gold: 0
    },
    3: {
      name: '',
      img: '',
      attack: 0,
      deffense: 0,
      specialatk: 0,
      specialdef: 0,
      specmoves: [],
      armor: 0,
      hp: 0,
      mp: 0,
      exp: 0,
      gold: 0
    },
    4: {
      name: '',
      img: '',
      attack: 0,
      deffense: 0,
      specialatk: 0,
      specialdef: 0,
      specmoves: [],
      armor: 0,
      hp: 0,
      mp: 0,
      exp: 0,
      gold: 0
    }
  },
  ch6: {
    1: {
      name: '',
      img: '',
      attack: 0,
      deffense: 0,
      specialatk: 0,
      specialdef: 0,
      specmoves: [],
      armor: 0,
      hp: 0,
      mp: 0,
      exp: 0,
      gold: 0
    },
    2: {
      name: '',
      img: '',
      attack: 0,
      deffense: 0,
      specialatk: 0,
      specialdef: 0,
      specmoves: [],
      armor: 0,
      hp: 0,
      mp: 0,
      exp: 0,
      gold: 0
    },
    3: {
      name: '',
      img: '',
      attack: 0,
      deffense: 0,
      specialatk: 0,
      specialdef: 0,
      specmoves: [],
      armor: 0,
      hp: 0,
      mp: 0,
      exp: 0,
      gold: 0
    },
    4: {
      name: '',
      img: '',
      attack: 0,
      deffense: 0,
      specialatk: 0,
      specialdef: 0,
      specmoves: [],
      armor: 0,
      hp: 0,
      mp: 0,
      exp: 0,
      gold: 0
    }
  },
  ch7: {
    1: {
      name: '',
      img: '',
      attack: 0,
      deffense: 0,
      specialatk: 0,
      specialdef: 0,
      specmoves: [],
      armor: 0,
      hp: 0,
      mp: 0,
      exp: 0,
      gold: 0
    },
    2: {
      name: '',
      img: '',
      attack: 0,
      deffense: 0,
      specialatk: 0,
      specialdef: 0,
      specmoves: [],
      armor: 0,
      hp: 0,
      mp: 0,
      exp: 0,
      gold: 0
    },
    3: {
      name: '',
      img: '',
      attack: 0,
      deffense: 0,
      specialatk: 0,
      specialdef: 0,
      specmoves: [],
      armor: 0,
      hp: 0,
      mp: 0,
      exp: 0,
      gold: 0
    },
    4: {
      name: '',
      img: '',
      attack: 0,
      deffense: 0,
      specialatk: 0,
      specialdef: 0,
      specmoves: [],
      armor: 0,
      hp: 0,
      mp: 0,
      exp: 0,
      gold: 0
    }
  }
}