export const boses = {
  ch1: {
    name: 'Staple Man',
    img: '',
    attack: 0,
    deffense: 0,
    specialatk: 0,
    specialdef: 0,
    specmoves: [],
    armor: 0,
    hp: 0,
    mp: 0,
    exp: 0,
    gold: 0
  },
  ch2: {
    name: 'Seceratary Johnson',
    img: '',
    attack: 0,
    deffense: 0,
    specialatk: 0,
    specialdef: 0,
    specmoves: [],
    armor: 0,
    hp: 0,
    mp: 0,
    exp: 0,
    gold: 0
  },
  ch3: {
    name: 'Tina from Human Resources',
    img: '',
    attack: 0,
    deffense: 0,
    specialatk: 0,
    specialdef: 0,
    specmoves: [],
    armor: 0,
    hp: 0,
    mp: 0,
    exp: 0,
    gold: 0
  },
  ch4: {
    name: 'The Janitor',
    img: '',
    attack: 0,
    deffense: 0,
    specialatk: 0,
    specialdef: 0,
    specmoves: [],
    armor: 0,
    hp: 0,
    mp: 0,
    exp: 0,
    gold: 0
  },
  ch5: {
    name: 'Director of Pain',
    img: '',
    attack: 0,
    deffense: 0,
    specialatk: 0,
    specialdef: 0,
    specmoves: [],
    armor: 0,
    hp: 0,
    mp: 0,
    exp: 0,
    gold: 0
  },
  ch6: {
    name: 'The Vice President',
    img: '',
    attack: 0,
    deffense: 0,
    specialatk: 0,
    specialdef: 0,
    specmoves: [],
    armor: 0,
    hp: 0,
    mp: 0,
    exp: 0,
    gold: 0
  },
  ch7: {
    name: 'The Big B',
    img: '',
    attack: 0,
    deffense: 0,
    specialatk: 0,
    specialdef: 0,
    specmoves: [],
    armor: 0,
    hp: 0,
    mp: 0,
    exp: 0,
    gold: 0
  }
}